platform :ios, '8.0'    
target 'vPort' do
  pod 'AFNetworking', '2.6.3'
  pod 'CocoaLumberjack', '1.9.2'
  pod 'FMDB', '2.6.2'
  pod 'MJExtension', '3.0.13'
  pod 'MJRefresh', '3.1.12'
  pod 'Masonry', '1.0.2'
  pod 'OpenSSL', :git => 'https://github.com/bither/OpenSSL.git', :branch => 'master'
  pod 'Reachability', '3.1.1'
  pod 'SDWebImage', '3.8.1'        
end
